#############################################################################
# Makefile for building: Exif-Scout
# Generated by qmake (2.01a) (Qt 4.5.0) on: Tue Jul 13 14:02:12 2010
# Project:  Exif-Scout.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile Exif-Scout.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lexiv2 -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = exif-scout_window.cpp \
		main.cpp \
		clickQlabel.cpp moc_clickQlabel.cpp \
		moc_exif-scout_window.cpp
OBJECTS       = exif-scout_window.o \
		main.o \
		clickQlabel.o \
		moc_clickQlabel.o \
		moc_exif-scout_window.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		Exif-Scout.pro
QMAKE_TARGET  = Exif-Scout
DESTDIR       = 
TARGET        = Exif-Scout

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_exif-scout_layout.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Exif-Scout.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile Exif-Scout.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Exif-Scout.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Exif-Scout1.0.0 || $(MKDIR) .tmp/Exif-Scout1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Exif-Scout1.0.0/ && $(COPY_FILE) --parents clickQlabel.h exif-scout_window.h .tmp/Exif-Scout1.0.0/ && $(COPY_FILE) --parents exif-scout_window.cpp main.cpp clickQlabel.cpp .tmp/Exif-Scout1.0.0/ && $(COPY_FILE) --parents exif-scout_layout.ui .tmp/Exif-Scout1.0.0/ && (cd `dirname .tmp/Exif-Scout1.0.0` && $(TAR) Exif-Scout1.0.0.tar Exif-Scout1.0.0 && $(COMPRESS) Exif-Scout1.0.0.tar) && $(MOVE) `dirname .tmp/Exif-Scout1.0.0`/Exif-Scout1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Exif-Scout1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_clickQlabel.cpp moc_exif-scout_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_clickQlabel.cpp moc_exif-scout_window.cpp
moc_clickQlabel.cpp: clickQlabel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) clickQlabel.h -o moc_clickQlabel.cpp

moc_exif-scout_window.cpp: ui_exif-scout_layout.h \
		exif-scout_window.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) exif-scout_window.h -o moc_exif-scout_window.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_exif-scout_layout.h
compiler_uic_clean:
	-$(DEL_FILE) ui_exif-scout_layout.h
ui_exif-scout_layout.h: exif-scout_layout.ui
	/usr/bin/uic-qt4 exif-scout_layout.ui -o ui_exif-scout_layout.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

exif-scout_window.o: exif-scout_window.cpp exif-scout_window.h \
		ui_exif-scout_layout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exif-scout_window.o exif-scout_window.cpp

main.o: main.cpp exif-scout_window.h \
		ui_exif-scout_layout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

clickQlabel.o: clickQlabel.cpp clickQlabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clickQlabel.o clickQlabel.cpp

moc_clickQlabel.o: moc_clickQlabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clickQlabel.o moc_clickQlabel.cpp

moc_exif-scout_window.o: moc_exif-scout_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exif-scout_window.o moc_exif-scout_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

